name: Publish CI Docker images
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push ${{ matrix.image-name }} image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-name: [bionic, buster, focal, debian-testing]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile.${{ matrix.image-name }}
          tags: ${{ matrix.image-name }}-py3
          username: apoikos
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ganeti/ci
